# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: github-actions  # See documentation for possible values
    directory: / # Location of package manifests
    schedule:
      interval: weekly
    labels:
      - dependencies

  # dado que hay 2 dockerfiles
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: nuget
    directory: /backend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - backend

  - package-ecosystem: npm        # dependabot usa npm para leer pnpm-lock.yaml
    directory: /frontend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - frontend
