// <auto-generated />
using System;
using JAV_API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JAV_API.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527223441_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JAV_API.Domain.Entities.CierreCaja", b =>
                {
                    b.Property<int>("IdCierreCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Cierre_Caja");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCierreCaja"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("IdFiscal")
                        .HasColumnType("integer")
                        .HasColumnName("id_Fiscal");

                    b.Property<int>("IdJornadaCobro")
                        .HasColumnType("integer")
                        .HasColumnName("id_Jornada_Cobro");

                    b.Property<string>("UrlFirmaFiscal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_Firma_Fiscal");

                    b.Property<string>("UrlFirmaTesorero")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_Firma_Tesorero");

                    b.HasKey("IdCierreCaja");

                    b.HasIndex("IdFiscal");

                    b.HasIndex("IdJornadaCobro")
                        .IsUnique();

                    b.ToTable("Cierre_Caja", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Comprobante", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Comprobante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComprobante"));

                    b.Property<int>("Codigo")
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    b.Property<int>("IdPago")
                        .HasColumnType("integer")
                        .HasColumnName("id_Pago");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("IdComprobante");

                    b.HasIndex("IdPago")
                        .IsUnique();

                    b.ToTable("Comprobante", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Conexion", b =>
                {
                    b.Property<int>("IdConexion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Conexion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConexion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("IdDomicilio")
                        .HasColumnType("integer")
                        .HasColumnName("id_Domicilio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_Usuario");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("IdConexion");

                    b.HasIndex("IdDomicilio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Conexion", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Domicilio", b =>
                {
                    b.Property<int>("IdDomicilio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Domicilio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDomicilio"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calle");

                    b.Property<string>("CodigoBloque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_Bloque");

                    b.Property<int>("LoteCasa")
                        .HasColumnType("integer")
                        .HasColumnName("lote_Casa");

                    b.HasKey("IdDomicilio");

                    b.HasIndex("CodigoBloque", "LoteCasa")
                        .IsUnique();

                    b.ToTable("Domicilio", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.DomicilioUsuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_Usuario");

                    b.Property<int>("IdDomicilio")
                        .HasColumnType("integer")
                        .HasColumnName("id_Domicilio");

                    b.Property<int>("Estructura")
                        .HasColumnType("integer")
                        .HasColumnName("estructura");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.HasKey("IdUsuario", "IdDomicilio", "Estructura");

                    b.HasIndex("IdDomicilio");

                    b.ToTable("Domicilio_Usuario", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Egreso", b =>
                {
                    b.Property<int>("IdEgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Egreso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEgreso"));

                    b.Property<int>("AprobadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("aprobado_Por");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<int>("RegistradoPor")
                        .HasColumnType("integer")
                        .HasColumnName("registrado_Por");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("IdEgreso");

                    b.HasIndex("AprobadoPor");

                    b.HasIndex("RegistradoPor");

                    b.ToTable("Egresos", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.HistorialCostos", b =>
                {
                    b.Property<int>("IdCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Cobro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCobro"));

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_Anulacion");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_Emision");

                    b.Property<int>("IdTipoCobro")
                        .HasColumnType("integer")
                        .HasColumnName("id_Tipo_Cobro");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("IdCobro");

                    b.HasIndex("IdTipoCobro");

                    b.ToTable("HistorialCostos", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.JornadaCobro", b =>
                {
                    b.Property<int>("IdJornadaCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Jornada_Cobro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdJornadaCobro"));

                    b.Property<int>("Encargado")
                        .HasColumnType("integer")
                        .HasColumnName("encargado");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.HasKey("IdJornadaCobro");

                    b.HasIndex("Encargado");

                    b.ToTable("Jornada_Cobro", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Mensualidad", b =>
                {
                    b.Property<int>("IdMensualidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Mensualidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMensualidad"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_Vencimiento");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_Usuario");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<DateTime?>("PeriodoPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo_Pago");

                    b.HasKey("IdMensualidad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Mensualidad", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Multa", b =>
                {
                    b.Property<int>("IdMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Multa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMulta"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("IdTipoMulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_Tipo_Multa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_Usuario");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("IdMulta");

                    b.HasIndex("IdTipoMulta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Multa", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_Pago");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metodo_Pago");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<int?>("RegistradoPor")
                        .HasColumnType("integer")
                        .HasColumnName("registrado_Por");

                    b.HasKey("IdPago");

                    b.HasIndex("RegistradoPor");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.PagoConexion", b =>
                {
                    b.Property<int>("IdConexion")
                        .HasColumnType("integer")
                        .HasColumnName("id_Conexion");

                    b.Property<int>("IdPago")
                        .HasColumnType("integer")
                        .HasColumnName("id_Pago");

                    b.HasKey("IdConexion", "IdPago");

                    b.HasIndex("IdPago");

                    b.ToTable("Pago_Conexion", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.PagoMensualidad", b =>
                {
                    b.Property<int>("IdMensualidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_Mensualidad");

                    b.Property<int>("IdPago")
                        .HasColumnType("integer")
                        .HasColumnName("id_Pago");

                    b.HasKey("IdMensualidad", "IdPago");

                    b.HasIndex("IdPago");

                    b.ToTable("Pago_Mensualidad", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.PagoMulta", b =>
                {
                    b.Property<int>("IdMulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_Multa");

                    b.Property<int>("IdPago")
                        .HasColumnType("integer")
                        .HasColumnName("id_Pago");

                    b.HasKey("IdMulta", "IdPago");

                    b.HasIndex("IdPago");

                    b.ToTable("Pago_Multa", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Permiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdPermiso");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Persona");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primer_Apellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primer_Nombre");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("segundo_Apellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("segundo_Nombre");

                    b.HasKey("IdPersona");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.TipoCobro", b =>
                {
                    b.Property<int>("IdTipoCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Tipo_Cobro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoCobro"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("IdTipoCobro");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Tipo_Cobro", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Tipo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Tipo_Usuario", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.TipoUsuarioPermiso", b =>
                {
                    b.Property<int>("IdTipo")
                        .HasColumnType("integer")
                        .HasColumnName("id_Tipo");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer")
                        .HasColumnName("id_Permiso");

                    b.HasKey("IdTipo", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("Tipo_Usuario_Permiso", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_Usuario");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_Creacion");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_Usuario");

                    b.Property<string>("Rol")
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_Acceso");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdTipoUsuario");

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.CierreCaja", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Usuario", "Fiscal")
                        .WithMany("CierresCajaFiscal")
                        .HasForeignKey("IdFiscal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.JornadaCobro", "JornadaCobro")
                        .WithOne("CierreCaja")
                        .HasForeignKey("JAV_API.Domain.Entities.CierreCaja", "IdJornadaCobro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fiscal");

                    b.Navigation("JornadaCobro");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Comprobante", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Pago", "Pago")
                        .WithOne("Comprobante")
                        .HasForeignKey("JAV_API.Domain.Entities.Comprobante", "IdPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Conexion", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Domicilio", "Domicilio")
                        .WithMany("Conexiones")
                        .HasForeignKey("IdDomicilio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Conexiones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domicilio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.DomicilioUsuario", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Domicilio", "Domicilio")
                        .WithMany("DomicilioUsuarios")
                        .HasForeignKey("IdDomicilio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("DomicilioUsuarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domicilio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Egreso", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Usuario", "Aprobador")
                        .WithMany("EgresosAprobados")
                        .HasForeignKey("AprobadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.Usuario", "Registrador")
                        .WithMany("EgresosRegistrados")
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aprobador");

                    b.Navigation("Registrador");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.HistorialCostos", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.TipoCobro", "TipoCobro")
                        .WithMany("HistorialCostos")
                        .HasForeignKey("IdTipoCobro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCobro");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.JornadaCobro", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Usuario", "EncargadoUsuario")
                        .WithMany("JornadasCobroEncargado")
                        .HasForeignKey("Encargado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EncargadoUsuario");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Mensualidad", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Mensualidades")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Multa", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.TipoCobro", "TipoMulta")
                        .WithMany("Multas")
                        .HasForeignKey("IdTipoMulta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Multas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoMulta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Pago", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Usuario", "Registrador")
                        .WithMany("PagosRegistrados")
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Registrador");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.PagoConexion", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Conexion", "Conexion")
                        .WithMany("PagoConexiones")
                        .HasForeignKey("IdConexion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.Pago", "Pago")
                        .WithMany("PagoConexiones")
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conexion");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.PagoMensualidad", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Mensualidad", "Mensualidad")
                        .WithMany("PagoMensualidades")
                        .HasForeignKey("IdMensualidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.Pago", "Pago")
                        .WithMany("PagoMensualidades")
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensualidad");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.PagoMulta", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Multa", "Multa")
                        .WithMany("PagoMultas")
                        .HasForeignKey("IdMulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.Pago", "Pago")
                        .WithMany("PagoMultas")
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Multa");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.TipoUsuarioPermiso", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.Permiso", "Permiso")
                        .WithMany("TipoUsuarioPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany("TipoUsuarioPermisos")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("JAV_API.Domain.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JAV_API.Domain.Entities.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("JAV_API.Domain.Entities.Usuario", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Conexion", b =>
                {
                    b.Navigation("PagoConexiones");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Domicilio", b =>
                {
                    b.Navigation("Conexiones");

                    b.Navigation("DomicilioUsuarios");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.JornadaCobro", b =>
                {
                    b.Navigation("CierreCaja");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Mensualidad", b =>
                {
                    b.Navigation("PagoMensualidades");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Multa", b =>
                {
                    b.Navigation("PagoMultas");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Pago", b =>
                {
                    b.Navigation("Comprobante");

                    b.Navigation("PagoConexiones");

                    b.Navigation("PagoMensualidades");

                    b.Navigation("PagoMultas");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("TipoUsuarioPermisos");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.TipoCobro", b =>
                {
                    b.Navigation("HistorialCostos");

                    b.Navigation("Multas");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.TipoUsuario", b =>
                {
                    b.Navigation("TipoUsuarioPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("JAV_API.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("CierresCajaFiscal");

                    b.Navigation("Conexiones");

                    b.Navigation("DomicilioUsuarios");

                    b.Navigation("EgresosAprobados");

                    b.Navigation("EgresosRegistrados");

                    b.Navigation("JornadasCobroEncargado");

                    b.Navigation("Mensualidades");

                    b.Navigation("Multas");

                    b.Navigation("PagosRegistrados");
                });
#pragma warning restore 612, 618
        }
    }
}
